"""
AD Assessment Run
=================

Production-safe bridge for ad-assessment.

This workflow does NOT execute AD cmdlets in the main AgentOS container.
Instead it:
1) creates a scenario package,
2) generates PowerShell scripts for user/runner execution,
3) optionally calls a separate assessment runner API.
"""

import json
import uuid
from datetime import UTC, datetime
from os import getenv
from pathlib import Path
from typing import Any
from urllib.error import URLError
from urllib.request import Request, urlopen

from agno.workflow.step import Step, StepInput, StepOutput
from agno.workflow.workflow import Workflow

from db import get_postgres_db


def _utc_now() -> str:
    return datetime.now(tz=UTC).isoformat()


def _as_bool(value: Any, default: bool = False) -> bool:
    if isinstance(value, bool):
        return value
    if isinstance(value, str):
        return value.strip().lower() in {"1", "true", "yes", "y", "on"}
    return default


def _as_int(value: Any, default: int) -> int:
    if isinstance(value, int):
        return value
    if isinstance(value, str):
        try:
            return int(value.strip())
        except ValueError:
            return default
    return default


def _load_payload(step_input: StepInput) -> dict[str, Any]:
    """Accepts JSON string or dict-like input and normalizes params."""
    raw = getattr(step_input, "input", None)
    if isinstance(raw, dict):
        return raw
    if isinstance(raw, str) and raw.strip():
        try:
            parsed = json.loads(raw)
            if isinstance(parsed, dict):
                return parsed
        except json.JSONDecodeError:
            return {"domain": raw.strip()}
    return {}


def _format_failure(title: str, details: list[str]) -> str:
    lines = [f"# {title}", "", "Overall: **FAIL**", ""]
    lines.extend(f"- {detail}" for detail in details)
    return "\n".join(lines)


def _http_get_json(url: str, timeout_seconds: int) -> tuple[bool, str]:
    request = Request(url=url, method="GET")
    try:
        with urlopen(request, timeout=timeout_seconds) as response:  # nosec: B310
            body = response.read().decode("utf-8", errors="replace")
            if response.status >= 400:
                return False, f"HTTP {response.status}: {body[:300]}"
            return True, body
    except URLError as exc:
        return False, str(exc)
    except Exception as exc:
        return False, str(exc)


def _http_post_json(url: str, payload: dict[str, Any], timeout_seconds: int) -> tuple[bool, str]:
    data = json.dumps(payload).encode("utf-8")
    request = Request(url=url, data=data, method="POST", headers={"Content-Type": "application/json"})
    try:
        with urlopen(request, timeout=timeout_seconds) as response:  # nosec: B310
            body = response.read().decode("utf-8", errors="replace")
            if response.status >= 400:
                return False, f"HTTP {response.status}: {body[:500]}"
            return True, body
    except URLError as exc:
        return False, str(exc)
    except Exception as exc:
        return False, str(exc)


def _safe_slug(text: str) -> str:
    keep = []
    for ch in text.lower().strip():
        if ch.isalnum() or ch in {"-", "_"}:
            keep.append(ch)
        elif ch in {" ", ".", "/", "\\"}:
            keep.append("-")
    slug = "".join(keep).strip("-")
    return slug or "scenario"


def _build_run_script(orchestrator_script: Path, output_dir: Path, scenario_file: Path, domain: str) -> str:
    return f"""# Auto-generated by AgentOS (ad-assessment-run)
param(
    [string]$ScenarioPath = \"{scenario_file}\",
    [string]$OrchestratorPath = \"{orchestrator_script}\",
    [string]$DefaultDomain = \"{domain}\"
)

$ErrorActionPreference = 'Stop'

if (-not (Test-Path -LiteralPath $ScenarioPath)) {{
    throw \"Scenario file not found: $ScenarioPath\"
}}
if (-not (Test-Path -LiteralPath $OrchestratorPath)) {{
    throw \"Orchestrator script not found: $OrchestratorPath\"
}}

$scenario = Get-Content -LiteralPath $ScenarioPath -Raw | ConvertFrom-Json
$domain = if ($scenario.domain) {{ $scenario.domain }} else {{ $DefaultDomain }}
$includePki = [bool]$scenario.include_pki
$generateMermaid = [bool]$scenario.generate_mermaid

if (-not (Test-Path -LiteralPath \"{output_dir}\")) {{
    New-Item -Path \"{output_dir}\" -ItemType Directory -Force | Out-Null
}}

$params = @{{
    DomainName = $domain
    UnixOutputPath = \"{output_dir}\"
    WindowsOutputPath = \"{output_dir}\"
}}

if ($includePki) {{ $params['IncludePKI'] = $true }}
if ($generateMermaid) {{ $params['GenerateMermaid'] = $true }}

Write-Host \"[ad-assessment] Running scenario '$($scenario.scenario_id)' for domain '$domain'...\" -ForegroundColor Cyan
& $OrchestratorPath @params

Write-Host \"[ad-assessment] Done. Artifacts at: {output_dir}\" -ForegroundColor Green
"""


def _build_llama_verify_script(expected_image: str, llama_base_url: str) -> str:
    return f"""# Auto-generated by AgentOS (llama runtime verification)
param(
    [string]$ContainerName = 'oia-runtime-llama-1',
    [string]$ExpectedImage = '{expected_image}',
    [string]$LlamaBaseUrl = '{llama_base_url}'
)

$ErrorActionPreference = 'Stop'

Write-Host \"[check] Inspecting container: $ContainerName\" -ForegroundColor Cyan
$inspect = docker inspect $ContainerName | ConvertFrom-Json
if (-not $inspect -or $inspect.Count -eq 0) {{ throw 'Container not found.' }}

$cfg = $inspect[0]
$image = $cfg.Config.Image
$running = $cfg.State.Running
$deviceReq = $cfg.HostConfig.DeviceRequests

if ($image -ne $ExpectedImage) {{
    throw \"Unexpected image. Found '$image', expected '$ExpectedImage'\"
}}
if (-not $running) {{
    throw \"Container is not running. Current status: $($cfg.State.Status)\"
}}
if (-not $deviceReq) {{
    throw 'No GPU device request found in HostConfig.DeviceRequests.'
}}

$caps = $deviceReq[0].Capabilities
$gpuFlag = $false
foreach ($capGroup in $caps) {{
    if ($capGroup -contains 'gpu') {{ $gpuFlag = $true }}
}}
if (-not $gpuFlag) {{
    throw 'Container is not requesting GPU capability.'
}}

Write-Host \"[check] Calling llama endpoint: $LlamaBaseUrl/v1/models\" -ForegroundColor Cyan
$models = Invoke-RestMethod -Method Get -Uri ($LlamaBaseUrl.TrimEnd('/') + '/v1/models') -TimeoutSec 10
if (-not $models) {{ throw 'Failed to query /v1/models.' }}

Write-Host '[ok] Llama runtime is using expected image + GPU request + OpenAI endpoint is reachable.' -ForegroundColor Green
"""


def _build_runner_submit_script(runner_url: str, scenario_file: Path, job_dir: Path) -> str:
    return f"""# Auto-generated by AgentOS (optional runner submit)
param(
    [string]$RunnerUrl = '{runner_url}',
    [string]$ScenarioPath = '{scenario_file}',
    [string]$JobDir = '{job_dir}'
)

$ErrorActionPreference = 'Stop'

if (-not (Test-Path -LiteralPath $ScenarioPath)) {{
    throw \"Scenario file not found: $ScenarioPath\"
}}

$payload = @{{
    scenario = Get-Content -LiteralPath $ScenarioPath -Raw | ConvertFrom-Json
    job_dir = $JobDir
}} | ConvertTo-Json -Depth 10

Invoke-RestMethod -Method Post -Uri $RunnerUrl -ContentType 'application/json' -Body $payload -TimeoutSec 30
Write-Host '[ok] Scenario submitted to runner.' -ForegroundColor Green
"""


def _write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


async def ad_assessment_run_step(step_input: StepInput) -> StepOutput:
    payload = _load_payload(step_input)

    domain = str(payload.get("domain") or getenv("AD_ASSESSMENT_DEFAULT_DOMAIN", "test.com")).strip()
    include_pki = _as_bool(payload.get("include_pki"), default=_as_bool(getenv("AD_ASSESSMENT_INCLUDE_PKI", "false")))
    generate_mermaid = _as_bool(
        payload.get("generate_mermaid"), default=_as_bool(getenv("AD_ASSESSMENT_GENERATE_MERMAID", "false"))
    )
    scenario_name = str(payload.get("scenario_name") or f"Assessment {domain}").strip()
    scenario_description = str(
        payload.get("scenario_description")
        or "Avaliação READ-ONLY de AD/DNS com correlação causal e geração de evidências."
    ).strip()

    assessment_root = Path(getenv("AD_ASSESSMENT_ROOT", "/workspace/ad-assessment"))
    orchestrator_script = assessment_root / "agents" / "orchestrator" / "OrchestratorAgent.ps1"
    output_root = Path(getenv("AD_ASSESSMENT_OUTPUT_PATH", "/tmp/ad-assessment-output"))

    llama_base_url = getenv("LLAMA_BASE_URL", "http://llama:8080").rstrip("/")
    llama_base_url_host = getenv("LLAMA_BASE_URL_HOST", "http://127.0.0.1:18080").rstrip("/")
    llama_models_url = f"{llama_base_url}/v1/models"
    llama_expected_image = getenv("LLAMA_CONTAINER_IMAGE", "oia-llama-full-cuda13-tools:local")
    llama_health_timeout = _as_int(getenv("LLAMA_HEALTH_TIMEOUT_SECONDS", "8"), default=8)

    runner_url = str(payload.get("runner_url") or getenv("AD_ASSESSMENT_RUNNER_URL", "")).strip()
    runner_timeout_seconds = _as_int(getenv("AD_ASSESSMENT_RUNNER_TIMEOUT_SECONDS", "20"), default=20)

    failures: list[str] = []
    warnings: list[str] = []

    if not domain:
        failures.append("Parâmetro obrigatório ausente: domain")
    if not assessment_root.exists():
        failures.append(
            f"AD_ASSESSMENT_ROOT não encontrado: {assessment_root}. "
            "Monte o repositório ad-assessment neste caminho no container/host do AgentOS."
        )
    if not orchestrator_script.exists():
        failures.append(f"Script do orquestrador não encontrado: {orchestrator_script}")

    if failures:
        return StepOutput(
            content=_format_failure("AD Assessment Run", failures),
            success=False,
        )

    output_root.mkdir(parents=True, exist_ok=True)

    scenario_id = f"{_safe_slug(scenario_name)}-{uuid.uuid4().hex[:8]}"
    job_dir = output_root / "jobs" / scenario_id
    scripts_dir = job_dir / "scripts"
    artifacts_dir = job_dir / "artifacts"
    scripts_dir.mkdir(parents=True, exist_ok=True)
    artifacts_dir.mkdir(parents=True, exist_ok=True)

    scenario = {
        "scenario_id": scenario_id,
        "scenario_name": scenario_name,
        "scenario_description": scenario_description,
        "created_at": _utc_now(),
        "domain": domain,
        "include_pki": include_pki,
        "generate_mermaid": generate_mermaid,
        "assessment_root": str(assessment_root),
        "orchestrator_script": str(orchestrator_script),
        "output_path": str(artifacts_dir),
        "execution_mode": "runner-separated",
        "read_only": True,
    }

    scenario_file = job_dir / "scenario.json"
    run_script = scripts_dir / "run-ad-assessment.ps1"
    verify_llama_script = scripts_dir / "verify-llama-cuda.ps1"
    submit_runner_script = scripts_dir / "submit-to-runner.ps1"

    _write_text(scenario_file, json.dumps(scenario, ensure_ascii=False, indent=2))
    _write_text(
        run_script,
        _build_run_script(
            orchestrator_script=orchestrator_script,
            output_dir=artifacts_dir,
            scenario_file=scenario_file,
            domain=domain,
        ),
    )
    _write_text(verify_llama_script, _build_llama_verify_script(llama_expected_image, llama_base_url_host))
    _write_text(submit_runner_script, _build_runner_submit_script(runner_url or "http://<runner-host>/run", scenario_file, job_dir))

    llama_ok, llama_info = _http_get_json(llama_models_url, timeout_seconds=llama_health_timeout)
    if not llama_ok:
        warnings.append(
            f"Llama endpoint não respondeu em {llama_models_url}. Detalhe: {llama_info}. "
            "Execute verify-llama-cuda.ps1 no host para diagnóstico de GPU/CUDA." 
        )

    runner_triggered = False
    runner_result = "runner não acionado (configure AD_ASSESSMENT_RUNNER_URL ou runner_url no payload)."
    if runner_url:
        payload_to_runner = {
            "job_id": scenario_id,
            "scenario": scenario,
            "scenario_path": str(scenario_file),
            "run_script_path": str(run_script),
            "artifacts_path": str(artifacts_dir),
        }
        ok, response = _http_post_json(runner_url, payload_to_runner, timeout_seconds=runner_timeout_seconds)
        runner_triggered = True
        if ok:
            runner_result = f"runner acionado com sucesso: {runner_url}"
        else:
            runner_result = f"falha ao acionar runner: {response}"
            warnings.append(
                "Runner externo configurado, porém indisponível. "
                "Use run-ad-assessment.ps1 manualmente no host com AD cmdlets."
            )

    status = "PASS" if not failures else "FAIL"

    lines = [
        "# AD Assessment Run",
        "",
        f"Overall: **{status}**",
        "",
        f"- created_at: `{_utc_now()}`",
        f"- execution_mode: `runner-separated`",
        f"- domain: `{domain}`",
        f"- include_pki: `{str(include_pki).lower()}`",
        f"- generate_mermaid: `{str(generate_mermaid).lower()}`",
        f"- scenario_id: `{scenario_id}`",
        f"- assessment_root: `{assessment_root}`",
        f"- job_dir: `{job_dir}`",
        f"- runner_triggered: `{str(runner_triggered).lower()}`",
        f"- runner_result: `{runner_result}`",
        f"- llama_base_url_internal: `{llama_base_url}`",
        f"- llama_base_url_host: `{llama_base_url_host}`",
        f"- llama_models_endpoint_reachable: `{str(llama_ok).lower()}`",
        "",
        "## Arquivos gerados",
        f"- scenario: `{scenario_file}`",
        f"- run script: `{run_script}`",
        f"- verify llama script: `{verify_llama_script}`",
        f"- runner submit script: `{submit_runner_script}`",
        f"- artifacts output folder: `{artifacts_dir}`",
    ]

    if warnings:
        lines.append("")
        lines.append("## Avisos")
        lines.extend([f"- {warn}" for warn in warnings])

    lines.extend(
        [
            "",
            "## Próximos passos (usuário)",
            "1. Revise o scenario.json e ajuste o escopo da avaliação.",
            "2. Execute `verify-llama-cuda.ps1` no host para validar GPU/CUDA e endpoint do llama.cpp.",
            "3. Execute `run-ad-assessment.ps1` no runner/host com módulos AD (RSAT) e conectividade ao domínio.",
            "4. Colete os artefatos JSON/CSV/HTML no diretório `artifacts` e reimporte no AgentOS para análise.",
        ]
    )

    return StepOutput(content="\n".join(lines), success=status == "PASS")


ad_assessment_run = Workflow(
    id="ad-assessment-run",
    name="AD Assessment Run",
    db=get_postgres_db(),
    steps=[Step(name="ad-assessment-run", executor=ad_assessment_run_step)],
)
